### ISSUE TITLE
tic tac toe

### ISSUE THREAD

**Issue by gbarzilay** [tocodeil/python-course-examples#113]
Are we supposed to use the unittest in the 27_tictactoe folder (test_board.py )?
It assumes a very specific implementation - different than described here
winner – is a function or property? Should I define checkWinner function? Game.data should be defined as array of arrays of Players? etc

**Comment by szabgab** [comment]
Using those unittests would be the default, but if you have another implementation that you feel is better then feel free to submit that with the appropriate unittests.

**Comment by szabgab** [comment]
As you cannot submit your own spec.py file, if you still want to have your own model, then I'd still suggest to write your own spec.py and post it as an attachment. to the pull-request. I think you can do that and then I can check it on my own end even if the Travis-CI will fail.
