### ISSUE TITLE
pydoc

### ISSUE THREAD

**Issue by LiatKotigaro** [tocodeil/python-course-examples#24]
pydoc doesn't recognized from the command line. Am I missing something? I get the error: 'pydoc' is not recognized as an internal or external command,
operable program or batch file.

**Comment by szabgab** [comment]
It might be some installation issue. You can create a file called `pydoc.bat` with  content that looks like this: (Just with the correct path to pydoc.py in your installation:

```
@python c:\Python27\Lib\pydoc.py %*
```

and put it somewhere in your PATH.

Then pydoc should work on the command line.

Personally I usually rely on Google searches and reading the docs on https://docs.python.org/
