### ISSUE TITLE
למה יש ארור בבדיקה

### ISSUE THREAD

**Issue by ygolan99** [tocodeil/python-course-examples#49]
D:\Users\ygolan\PycharmProjects\Verint_Pythone_course>python spec.py
...max number = 10.000000
max number = 10.000000
max number = 10.000000
max number = 10.000000
max number = 10.000000
max number = 10.000000
max number = 10.000000
max number = 10.000000
max number = 10.000000
max number = 10.000000
.... the random number is: 7
the sum of the digits is: 7
...E..
======================================================================
ERROR: test_find_number (__main__.TestEx5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\mock\mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "spec.py", line 106, in test_find_number
    execfile('05.py')
  File "05.py", line 13, in <module>
    exit()
  File "C:\Python27\lib\site.py", line 360, in __call__
    raise SystemExit(code)
SystemExit: None

----------------------------------------------------------------------

התוכנית שלי היא:
import random

while True:
    numbers = (random.randint(1, 1000000))

    if numbers % 7 and numbers % 13 and numbers % 15 == 0:
        print "Num " + str(numbers) + " is divided 7, 13, 15"
        exit()

**Comment by szabgab** [comment]
It is a bit hard to see this way, please put the whole code in triple-backtick when pasting here or submit them as a solution with a comment on the Pull-request that you need help

**Comment by ygolan99** [comment]
please run spec.py on 05.py and see

**Comment by szabgab** [comment]
See #27
