### ISSUE TITLE
pip

### ISSUE THREAD

**Issue by gbarzilay** [tocodeil/python-course-examples#9]
לא יכלתי להריץ פשוט pip. הרצתי c:\Python27\Scripts\pip 
כנ"ל לגבי pydoc
האם חסר לי משהו ב path? או בעיה אחרת?

**Comment by ynonp** [comment]
בהחלט ייתכן-
נסה להוסיף את תיקיית 
C:\Python27\Scripts

ל path 
וספר אם זה מסתדר

כאן יש הוראות איך להוסיף תיקיה ל path:
http://windowsitpro.com/systems-management/how-can-i-add-new-folder-my-system-path
